<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.jpstale.server</groupId>
        <artifactId>jpstale-parent</artifactId>
        <version>${jpstale.version}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>app</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>game-server</module>
        <module>web-server</module>
    </modules>

</project>